# JavaScript-SBA-308

check my code in solution-1-v1.js




also put the try/catch inside and at the beginning of the function getLearnerData, it worked.
but in order for the readability,try/catch was decided to put outside the function